apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "helm-canarydemo.fullname" . }}
  labels:
    app: {{ template "helm-canarydemo.name" . }}
    chart: {{ template "helm-canarydemo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {{- include "helm-canarydemo.pauseDuration" . | nindent 14 }}
        - setWeight: 50
        - pause: {duration: 30s}
        - setWeight: 70
        - pause: {duration: 30s}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ template "helm-canarydemo.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "helm-canarydemo.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m