name: deploy using canary strategy
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
on:
  workflow_dispatch:
    inputs:
      release-name:
        description: Helm release name
        type: string
        required: true
      env:
        description: Environment name to deploy on
        type: string
        required: true
        default: prod  
      namespace:
        description: Kubernetes namespace to install the chart in, created if missing
        type: string
        default: default
      cluster:
        description: Kubernetes cluster to install the chart in
        type: string  
        required: true
      artifact-id:
        description: artifact version UUID to be installed
        type: string
      timeout:
        description: |
          Helm chart installation timeout.
          However, `Deployment.spec.progressDeadlineSeconds` takes precedence if it is defined with a lower value within the charts manifests.
        type: string
        default: 10m
      chart-location:
        description: |
          Helm chart location, can be a URL, a local chart archive, chart repo alias/chart name or an unpacked chart directory
        type: string
        required: true
      pause:
        description: Whether to pause for canary verification
        type: boolean
        default: true
      aws-region:
        type: string
        required: true  
      aws-role-to-assume:
        type: string
        required: true
  workflow_call:
    inputs:
      release-name:
        description: Helm release name
        type: string
        required: true
      env:
        description: Environment name to deploy on
        type: string
        required: true
        default: prod  
      namespace:
        description: Kubernetes namespace to install the chart in, created if missing
        type: string
        default: default
      cluster:
        description: Kubernetes cluster to install the chart in
        type: string  
        required: true  
      artifact-id:
        description: Artifact version UUID to be installed
        type: string
      timeout:
        description: |
          Helm chart installation timeout.
          However, `Deployment.spec.progressDeadlineSeconds` takes precedence if it is defined with a lower value within the charts manifests.
        type: string
        default: 10m
      chart-location:
        description: |
          Helm chart location, can be a URL, a local chart archive, chart repo alias/chart name or an unpacked chart directory
        type: string
        required: true
      pause:
        description: Whether to pause for canary verification
        type: boolean
        default: true
      aws-region:
        type: string
        required: true   
      aws-role-to-assume:
        type: string
        required: true
jobs:
  get-version:
    outputs:
      version: ${{ steps.get-artifact-details.outputs.version }}
    steps:
      - id: get-artifact-details
        uses: cloudbees-io/get-artifact-details@v1
        with:
          artifact-id: ${{ inputs.artifact-id }}
  deploy:
    needs: get-version
    outputs:
      request-approval: ${{ steps.rollout.outputs.request-approval }}
      status: ${{ steps.rollout.outputs.status }}
    permissions:
      scm-token-own: read
      id-token: write
    steps:
      - name: Login to AWS
        uses: https://github.com/cloudbees-io/configure-aws-credentials@v1
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.aws-role-to-assume }}
          role-duration-seconds: "3600"
      - uses: cloudbees-io/configure-eks-credentials@v1
        with:
          name: ${{ inputs.cluster }}
      - uses: cloudbees-io/checkout@v1
        with:
          repository: https://github.com/urvashisingh/deployment-strategies
      - name: Create values.yaml 
        uses: docker://alpine/k8s:1.30.2
        run: |
          set -u
          echo "image:" > $CLOUDBEES_WORKSPACE/values.yaml
          echo "  tag: ${{ needs.get-version.outputs.version }}" >> $CLOUDBEES_WORKSPACE/values.yaml
          echo "pauseIndefinitely: ${{ inputs.pause }}" >> $CLOUDBEES_WORKSPACE/values.yaml
          cat $CLOUDBEES_WORKSPACE/values.yaml
      - name: K8S cluster details
        uses: docker://alpine/k8s:1.33.4
        run: |
          set -u
          kubectl version
          kubectl cluster-info dump
      - name: Deploy Helm chart
        uses: cloudbees-io/helm-install@v1
        with:
          release-name: ${{ inputs.release-name }}
          namespace: ${{ inputs.namespace }}
          values-files: values.yaml
          timeout: ${{ inputs.timeout }}
          chart-location: ${{ inputs.chart-location }}
          debug: true
          wait: true
      - name: Watch Rollout progress
        id: rollout
        env:
          JWT: ${{ cloudbees.api.token }}
          CB_API_URL: ${{ cloudbees.api.url }}
          CB_RUN_ID: ${{ cloudbees.run_id }}
          CB_RUN_ATTEMPT: ${{ cloudbees.run_attempt }}
          ENVIRONMENT: ${{ inputs.env }}
          DEBUG: "true"
        uses: docker://alpine/k8s:1.32.11
        run: |
          set -u

          function register_deployment() {
            local artifact_id="$1" 
            local command_failed=0

            PAYLOAD=$(jq --null-input \
            --arg artifact_id "$artifact_id" \
            --arg runId "$CB_RUN_ID" \
            --arg runAttempt "$CB_RUN_ATTEMPT" \
            --arg environment "$ENVIRONMENT" \
            '{"runId": $runId, "runAttempt": $runAttempt, "artifact_id": $artifact_id, "environment": $environment}')

            response=$(curl --silent --show-error --fail-with-body  -X 'POST' "$CB_API_URL/v3/deployments" \
              -H "Authorization: Bearer $JWT" \
              -H 'Content-Type: application/json' \
              -d "$PAYLOAD") || command_failed=1

            if [ ${command_failed:-0} -eq 1 ];
            then
              echo "Failed to add deployment for artifact_id: $artifact_id, error: '$response'"
            fi  
          }

          function publish_evidence() {
            local evidence=$1
            local command_failed=0

            PAYLOAD=$(jq --null-input \
            --arg evidence "$evidence" \
            --arg runId "$CB_RUN_ID" \
            --arg runAttempt "$CB_RUN_ATTEMPT" \
            '{"runId": $runId, "runAttempt": $runAttempt, "evidence": {"format": "MARKDOWN", "value": $evidence}}')

            response=$(curl --retry 5 --retry-delay 10 --retry-all-errors --silent --show-error --fail-with-body \
              -X 'POST' "$CB_API_URL/v1/workflows/artifact" \
              -H "Authorization: Bearer $JWT" \
              -H 'Content-Type: application/json' \
              -d "$PAYLOAD") || command_failed=1

            if [ ${command_failed:-0} -eq 1 ];
            then
              echo "Failed to publish workflow evidence, error: '$response'"
            fi
          }

          progressing=true
          request_approval=false
          status=""

          previous_status=""
          previous_step=""
          previous_replicas=""

          while $progressing; do
            sleep 10
            rollout_output="$(kubectl get rollout ${{ inputs.release-name }}-canary-demo -n ${{ inputs.namespace }} -o json)"
            status="$(echo "$rollout_output" | jq -r '.status.phase')"
            is_canary="$(echo "$rollout_output" | jq '.spec.strategy | has("canary")')"
            is_bluegreen="$(echo "$rollout_output" | jq '.spec.strategy | has("blueGreen")')"
            strategy_type=""
            if [ "$is_canary" = "true" ]; then
              strategy_type="Canary"
            elif [ "$is_bluegreen" = "true" ]; then
              strategy_type="Blue-green"
            fi
            
            total_replicas="$(echo "$rollout_output" | jq -r '.spec.replicas')"
            canary_replicas="$(echo "$rollout_output" | jq -r '.status.updatedReplicas')"
            total_steps="$(echo "$rollout_output" | jq -r '.spec.strategy.canary.steps | length')"
            current_step="$(echo "$rollout_output" | jq -r '.status.currentStepIndex')"
            # Add 1 to current step for human-friendly display but not if in Healthy because then rollout is complete and current index is at total step count
            if [[ "$status" != "Healthy" ]]; then
              current_step=$((current_step + 1))
            fi

            echo "Status: $status"
            if [ "$DEBUG" = "true" ]; then
                echo "Rollout output: $rollout_output"
            fi

            if [[ "$status" == "Healthy" ]]; then
              progressing=false
            elif [[ "$status" == "Degraded" ]]; then
              progressing=false
            elif [[ "$status" == "Paused" ]]; then
              duration="$(echo "$rollout_output" | jq -r '.spec.strategy.canary.steps[.status.currentStepIndex].pause.duration')"
              echo "Pause duration: $duration"
              if [[ "$duration" == "" || "$duration" == "null" ]]; then
                progressing=false
                request_approval=true
              fi                              
            fi

            if [[ "$status" == "Degraded" ]]; then
              publish_evidence "ERROR: Version: ${{ needs.get-version.outputs.version }} deployment failed"
              echo "ERROR: Version: ${{ needs.get-version.outputs.version }} deployment failed"
              echo "$rollout_output"
              kubectl get pods -n ${{ inputs.namespace }}
              exit -1
            fi
          
            # Register deployment if we are getting the status for the first time
            # Else only update the deployment status if there is a change
            if [[ -z "$previous_status" ]]; then
              register_deployment "${{ inputs.artifact-id }}"
              publish_evidence "Deployment strategy: $strategy_type"
            fi
            if [[ "$status" != "$previous_status" || "$current_step" != "$previous_step" || "$canary_replicas" != "$previous_replicas" ]]; then
              publish_evidence "Version: ${{ needs.get-version.outputs.version }}, Deployment status: $status, Step $current_step of $total_steps, Updated replicas $canary_replicas of $total_replicas"
            fi
            previous_status="$status"
            previous_step="$current_step"
            previous_replicas="$canary_replicas"
            
          done

          echo "$request_approval" > "$CLOUDBEES_OUTPUTS/request-approval"
          echo "$status" > "$CLOUDBEES_OUTPUTS/status"
  verify-canary:
    needs: deploy
    with:
      instructions: |
            Approve with `promote` to continue with the deployment if canary version looks good.
            Approve with `rollback` to abort the deployment and rollback in case the canary version is not good.
      disallowLaunchByUser: false
      approvers: ""
      notifyAllEligibleUsers: false
      approvalInputs: |
        action:
          type: choice
          default: promote
          options:
            - promote
            - rollback
          required: true
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
  complete-deployment:
    needs: 
      - verify-canary
      - get-version
    permissions:
      scm-token-own: read
      id-token: write
    steps:
      - name: Login to AWS
        uses: https://github.com/cloudbees-io/configure-aws-credentials@v1
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.aws-role-to-assume }}
          role-duration-seconds: "3600"
      - uses: cloudbees-io/configure-eks-credentials@v1
        with:
          name: ${{ inputs.cluster }}
      - name: Complete rollout
        uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/helm-install-action:e7ba2d12beccee417aad45b6aa50966b7b5c8c06
        env:
          ROLLOUT_ACTION: ${{ fromJSON(needs.verify-canary.outputs.approvalInputValues).action }}
        run: |
          set -u
          if [ "$ROLLOUT_ACTION" == "promote" ]; then
            kubectl-argo-rollouts promote ${{ inputs.release-name }}-canary-demo -n ${{ inputs.namespace }}
          else
            kubectl-argo-rollouts abort ${{ inputs.release-name }}-canary-demo -n ${{ inputs.namespace }}
          fi
      - name: Watch Rollout progress
        id: rollout
        env:
          JWT: ${{ cloudbees.api.token }}
          CB_API_URL: ${{ cloudbees.api.url }}
          CB_RUN_ID: ${{ cloudbees.run_id }}
          CB_RUN_ATTEMPT: ${{ cloudbees.run_attempt }}
          ENVIRONMENT: ${{ inputs.env }}
          ROLLOUT_ACTION: ${{ fromJSON(needs.verify-canary.outputs.approvalInputValues).action }}
          DEBUG: "true"
        uses: docker://alpine/k8s:1.32.11
        run: |
          set -u

          function register_deployment() {
            local artifact_id="$1" 
            local command_failed=0

            PAYLOAD=$(jq --null-input \
            --arg artifact_id "$artifact_id" \
            --arg runId "$CB_RUN_ID" \
            --arg runAttempt "$CB_RUN_ATTEMPT" \
            --arg environment "$ENVIRONMENT" \
            '{"runId": $runId, "runAttempt": $runAttempt, "artifact_id": $artifact_id, "environment": $environment}')

            response=$(curl --silent --show-error --fail-with-body  -X 'POST' "$CB_API_URL/v3/deployments" \
              -H "Authorization: Bearer $JWT" \
              -H 'Content-Type: application/json' \
              -d "$PAYLOAD") || command_failed=1

            if [ ${command_failed:-0} -eq 1 ];
            then
              echo "Failed to add deployment for artifact_id: $artifact_id, error: '$response'"
            fi  
          }

          function publish_evidence() {
            local evidence=$1
            local command_failed=0

            PAYLOAD=$(jq --null-input \
            --arg evidence "$evidence" \
            --arg runId "$CB_RUN_ID" \
            --arg runAttempt "$CB_RUN_ATTEMPT" \
            '{"runId": $runId, "runAttempt": $runAttempt, "evidence": {"format": "MARKDOWN", "value": $evidence}}')

            response=$(curl --retry 5 --retry-delay 10 --retry-all-errors --silent --show-error --fail-with-body \
              -X 'POST' "$CB_API_URL/v1/workflows/artifact" \
              -H "Authorization: Bearer $JWT" \
              -H 'Content-Type: application/json' \
              -d "$PAYLOAD") || command_failed=1

            if [ ${command_failed:-0} -eq 1 ];
            then
              echo "Failed to publish workflow evidence, error: '$response'"
            fi
          }

          progressing=true
          request_approval=false
          status=""
          rollout_output=""

          previous_status=""
          previous_step=""
          previous_replicas=""

          while $progressing; do
            sleep 10
            rollout_output="$(kubectl get rollout ${{ inputs.release-name }}-canary-demo -n ${{ inputs.namespace }} -o json)"
            status="$(echo "$rollout_output" | jq -r '.status.phase')"

            total_replicas="$(echo "$rollout_output" | jq -r '.spec.replicas')"
            canary_replicas="$(echo "$rollout_output" | jq -r '.status.updatedReplicas')"
            total_steps="$(echo "$rollout_output" | jq -r '.spec.strategy.canary.steps | length')"
            current_step="$(echo "$rollout_output" | jq -r '.status.currentStepIndex')"
            
            # Add 1 to current step for human-friendly display but not if in Healthy because then rollout is complete and current index is at total step count
            if [[ "$status" != "Healthy" ]]; then
              current_step=$((current_step + 1))
            fi

            echo "Status: $status"  
            if [ "$DEBUG" = "true" ]; then
                echo "Rollout output: $rollout_output"
            fi

            if [[ "$status" == "Healthy" ]]; then
              progressing=false
            elif [[ "$status" == "Degraded" ]]; then
              progressing=false
            elif [[ "$status" == "Paused" ]]; then
              duration="$(echo "$rollout_output" | jq -r '.spec.strategy.canary.steps[.status.currentStepIndex].pause.duration')"
              echo "Pause duration: $duration"
              if [[ "$duration" == "" || "$duration" == "null" ]]; then
                progressing=false
                request_approval=true
              fi                              
            fi

            if [[ "$status" != "$previous_status" || "$current_step" != "$previous_step" || "$canary_replicas" != "$previous_replicas" ]]; then
              if [ "$ROLLOUT_ACTION" == "promote" ]; then
                publish_evidence "Version: ${{ needs.get-version.outputs.version }}, Deployment status: $status, Step $current_step of $total_steps, Updated replicas $canary_replicas of $total_replicas"
              else 
                publish_evidence "Aborting rollout for version: ${{ needs.get-version.outputs.version }}, Deployment status: $status, Step $current_step of $total_steps, Updated replicas $canary_replicas of $total_replicas"
              fi
            fi
            

            previous_status="$status"
            previous_step="$current_step"
            previous_replicas="$canary_replicas"

          done

           if [ "$ROLLOUT_ACTION" == "promote" ]; then
            if [[ "$status" == "Healthy" ]]; then
              publish_evidence "Version: ${{ needs.get-version.outputs.version }} deployed successfully"
            elif [[ "$status" == "Degraded" ]]; then
              publish_evidence "ERROR: Version: ${{ needs.get-version.outputs.version }} deployment failed"
              echo "ERROR: Version: ${{ needs.get-version.outputs.version }} deployment failed"
              echo "$rollout_output"
              kubectl get pods -n ${{ inputs.namespace }}
              exit -1
            elif [[ "$status" == "Paused" ]]; then
              publish_evidence "WARNING: Version: ${{ needs.get-version.outputs.version }} deployment is paused indefinitely"
              exit -1    
            fi
          else  
            if [[ "$status" == "Healthy" ]]; then
              publish_evidence "Version: ${{ needs.get-version.outputs.version }} rolled back"
            elif [[ "$status" == "Degraded" ]]; then
              publish_evidence "ERROR: Version: ${{ needs.get-version.outputs.version }} roll back failed"
              echo "ERROR: Version: ${{ needs.get-version.outputs.version }} roll back failed"
              echo "$rollout_output"
              exit -1
            elif [[ "$status" == "Paused" ]]; then
              publish_evidence "WARNING: Version: ${{ needs.get-version.outputs.version }} deployment is paused indefinitely"
              exit -1    
            fi
          fi
  
