name: deploy using canary strategy
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

on:
  workflow_dispatch:
    inputs:
      release-name:
        description: Helm release name
        type: string
        required: true
      namespace:
        description: Kubernetes namespace to install the chart in, created if missing
        type: string
        default: default
      version:
        description: Version of the chart to be installed
        type: string
      values-files:
        description: List of values files relative to the workspace separated by newline
        type: string
      values:
        description: An inline YAML representation of a values file passed to the Helm command
        type: string
      timeout:
        description: |
          Helm chart installation timeout.
          However, `Deployment.spec.progressDeadlineSeconds` takes precedence if it is defined with a lower value within the charts manifests.
        type: string
        default: 10m
      chart-location:
        description: >
          Helm chart location, can be a URL, a local chart archive,
          chart repo alias/chart name or an unpacked chart directory
        type: string
        required: true
      debug:
        description: Execute the helm command in debug mode
        type: boolean
        default: false
      dry-run:
        description: Simulate an upgrade, without actually doing it
        type: boolean
        default: false
      aws-role-to-assume:
        type: string  
        
  workflow_call:
    inputs:
      release-name:
        description: Helm release name
        type: string
        required: true
      namespace:
        description: Kubernetes namespace to install the chart in, created if missing
        type: string
        default: default
      version:
        description: Version of the chart to be installed
        type: string
      values-files:
        description: List of values files relative to the workspace separated by newline
        type: string
      values:
        description: An inline YAML representation of a values file passed to the Helm command
        type: string
      timeout:
        description: |
          Helm chart installation timeout.
          However, `Deployment.spec.progressDeadlineSeconds` takes precedence if it is defined with a lower value within the charts manifests.
        type: string
        default: 10m
      chart-location:
        description: >
          Helm chart location, can be a URL, a local chart archive,
          chart repo alias/chart name or an unpacked chart directory
        type: string
        required: true
      debug:
        description: Execute the helm command in debug mode
        type: boolean
        default: false
      dry-run:
        description: Simulate an upgrade, without actually doing it
        type: boolean
        default: false
      aws-role-to-assume:
        type: string

        
jobs:
  deploy:
    permissions:
      scm-token-own: read
      id-token: write
    steps:
    - name: Login to AWS
      uses: https://github.com/cloudbees-io/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        role-duration-seconds: "3600"
    - uses: cloudbees-io/configure-eks-credentials@v1
      with:
        name: eks-app-preprod-us-east-1  
    - uses: cloudbees-io/checkout@v1
      with:
        repository: https://github.com/urvashisingh/deployment-strategies 

    - name: Deploy Helm chart
      uses: cloudbees-io/helm-install/.cloudbees/testing@argo-rollout
      with:
        release-name: ${{ inputs.release-name }}
        namespace: ${{ inputs.namespace }}
        version: ${{ inputs.version }}
        values-files: ${{ inputs.values-files }}
        values: ${{ inputs.values }}
        timeout: ${{ inputs.timeout }}
        chart-location: ./examples/helm-canary
        debug: ${{ inputs.debug }}
        wait: true
        dry-run: ${{ inputs.dry-run }}
