name: deploy using canary strategy
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
on:
  workflow_dispatch:
    inputs:
      release-name:
        description: Helm release name
        type: string
        required: true
      namespace:
        description: Kubernetes namespace to install the chart in, created if missing
        type: string
        default: default
      version:
        description: Version of the service to be installed
        type: string
      timeout:
        description: |
          Helm chart installation timeout.
          However, `Deployment.spec.progressDeadlineSeconds` takes precedence if it is defined with a lower value within the charts manifests.
        type: string
        default: 10m
      chart-location:
        description: |
          Helm chart location, can be a URL, a local chart archive, chart repo alias/chart name or an unpacked chart directory
        type: string
        required: true
      debug:
        description: Execute the helm command in debug mode
        type: boolean
        default: false
      dry-run:
        description: Simulate an upgrade, without actually doing it
        type: boolean
        default: false
      aws-role-to-assume:
        type: string
  workflow_call:
    inputs:
      release-name:
        description: Helm release name
        type: string
        required: true
      namespace:
        description: Kubernetes namespace to install the chart in, created if missing
        type: string
        default: default
      version:
        description: Version of the service to be installed
        type: string
      timeout:
        description: |
          Helm chart installation timeout.
          However, `Deployment.spec.progressDeadlineSeconds` takes precedence if it is defined with a lower value within the charts manifests.
        type: string
        default: 10m
      chart-location:
        description: |
          Helm chart location, can be a URL, a local chart archive, chart repo alias/chart name or an unpacked chart directory
        type: string
        required: true
      debug:
        description: Execute the helm command in debug mode
        type: boolean
        default: false
      dry-run:
        description: Simulate an upgrade, without actually doing it
        type: boolean
        default: false
      aws-role-to-assume:
        type: string
jobs:
  deploy:
    permissions:
      scm-token-own: read
      id-token: write
    steps:
      - name: Login to AWS
        uses: https://github.com/cloudbees-io/configure-aws-credentials@v1
        with:
          aws-region: ${{ vars.argo_rollout_cluster_region }}
          role-to-assume: ${{ vars.argo_rollout_staging_iam_role }}
          role-duration-seconds: "3600"
      - uses: cloudbees-io/configure-eks-credentials@v1
        with:
          name: ${{ vars.argo_rollout_east_cluster_name }}
      - uses: cloudbees-io/checkout@v1
        with:
          repository: https://github.com/urvashisingh/deployment-strategies
      - name: Create values.yaml with service version
        uses: docker://alpine/k8s:1.30.2
        run: |
          set -u
          echo "image:" > /tmp/values.yaml
          echo "  tag: ${{ inputs.version }}" >> /tmp/values.yaml
          cat /tmp/values.yaml
      - name: K8S cluster details
        uses: docker://alpine/k8s:1.30.2
        run: |
          set -u
          kubectl version
          kubectl cluster-info
      - name: Deploy Helm chart
        uses: cloudbees-io/helm-install@v1
        with:
          release-name: ${{ inputs.release-name }}
          namespace: ${{ inputs.namespace }}
          values-files: /tmp/values.yaml
          timeout: ${{ inputs.timeout }}
          chart-location: ${{ inputs.chart-location }}
          debug: ${{ inputs.debug }}
          wait: true
          dry-run: ${{ inputs.dry-run }}
      - name: Watch Rollout progress
        uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/helm-install-action:e7ba2d12beccee417aad45b6aa50966b7b5c8c06
        run: |
          set -u
          deploying=true

          while $deploying; do
            sleep 10
            status="$(kubectl argo rollouts -n ${{ inputs.namespace }} \
                                            --namespace="$KUBERNETES_NAMESPACE" \
                                            get rollout web | \
                                            grep 'Status' | \
                                            awk '{print $3}')"

            echo "Status: $status"

            if [ "$status" = "Healthy" ]; then
              deploying=false
            fi
          done
          kubectl -n ${{ inputs.namespace }} get rollout ${{ inputs.release-name }}-canary-demo
      - name: Checkout
        uses: cloudbees-io/checkout@v1
