name: deploy using canary strategy
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

on:
  workflow_call:
    inputs:
      release-name:
        description: Helm release name
        type: string
        required: true
      namespace:
        description: Kubernetes namespace to install the chart in, created if missing
        type: string
        default: default
      version:
        description: Version of the chart to be installed
        type: string
      values-files:
        description: List of values files relative to the workspace separated by newline
        type: string
      values:
        description: An inline YAML representation of a values file passed to the Helm command
        type: string
      timeout:
        description: |
          Helm chart installation timeout.
          However, `Deployment.spec.progressDeadlineSeconds` takes precedence if it is defined with a lower value within the charts manifests.
        type: string
        default: 10m
      chart-location:
        description: >
          Helm chart location, can be a URL, a local chart archive,
          chart repo alias/chart name or an unpacked chart directory
        type: string
        required: true
      max-history:
        description: MaxHistory limits the maximum number of revisions saved per release
        type: number
        default: 10
      debug:
        description: Execute the helm command in debug mode
        type: boolean
        default: false
      dependency-build:
        description: Build dependencies based on the contents of Chart.lock file
        type: boolean
        default: false
      env-vars-file:
        description: >
          An optional file with key value pairs of the format export key=value
          to export in the environment before execution of the helm commands.
        type: string
      dry-run:
        description: Simulate an upgrade, without actually doing it
        type: boolean
        default: false
      registry-configuration:
        description: >
          CloudBees registry configuration file containing the registries to use for loading images.
          By default it uses the file containing the registries configured under Integrations' in the CloudBees platform.
        type: string
        #default: ${{ cloudbees.registries }}
        
jobs:
  deploy:
    env:
      CHART_LOCATION: ${{ inputs.chart-location }}
      CHART_VERSION: ${{ inputs.version }}
      RELEASE_NAME: ${{ inputs.release-name }}
      VALUES_FILES: ${{ inputs.values-files }}
      VALUES_INLINE: ${{ inputs.values }}
      ENV_FILE: ${{ inputs.env-vars-file }}
      BUILD_DEPENDENCIES: ${{ inputs.dependency-build }}
      TIMEOUT: ${{ inputs.timeout }}
      HELM_NAMESPACE: ${{ inputs.namespace }}
      HELM_MAX_HISTORY: ${{ inputs.max-history }}
      HELM_DEBUG: ${{ inputs.debug == 'true' && 'true' || 'false' }}
      CLOUDBEES_REGISTRIES_CONFIG: ${{ inputs.registry-configuration }}
    steps:
    - name: Get Helm chart
      uses: docker://public.ecr.aws/l7o7z1g8/actions/helm-install-action:e0a374369133dba712a5239a3b78bb34c7828cc1
      run: |
        set -uox pipefail

        resolved_registries="/tmp/resolved_registries.out"

        if echo "${CHART_LOCATION}" | grep -q '^oci://'; then
          if [ "${CLOUDBEES_REGISTRIES_CONFIG}" ]; then
            chart_location=$(echo -n "${CHART_LOCATION}" | sed 's|^oci://||')
            registry-config --config "${CLOUDBEES_REGISTRIES_CONFIG}" resolve "${chart_location}" ${resolved_registries}
            echo "Resolved registries: $(cat ${resolved_registries})"
          fi
        fi

        if [ "$ENV_FILE" ]; then
          source "$ENV_FILE"
        fi

        if [ -s "${resolved_registries}" ]; then
          findChartInMirrors() {
            while IFS= read -r chart_location
            do
              chart_location=oci://$(echo "$chart_location" | awk -F':' '{print $1}') # strip the tag
              echo "Verifying chart location: $chart_location by running helm show"
              if helm show chart "$chart_location" --version "$CHART_VERSION"; then
                echo "Setting chart location to $chart_location"
                export CHART_LOCATION="$chart_location"
                return 0
              fi
            done < "${resolved_registries}"

            echo "Failed to find chart in any of the configured registry mirrors" >&2
            exit 1
          }

          findChartInMirrors
        fi

        mkdir -p $CLOUDBEES_WORKSPACE/helm-chart
        echo "Pulling Helm chart from $CHART_LOCATION into $CLOUDBEES_WORKSPACE/helm-chart"
        helm pull "$CHART_LOCATION" \
          --version "$CHART_VERSION" \
          --untar true \
          --untardir $CLOUDBEES_WORKSPACE/helm-chart
            
    - name: Deploy Helm chart
      uses: cloudbees-io/helm-install@v1
      with:
        release-name: ${{ inputs.release-name }}
        namespace: ${{ inputs.namespace }}
        version: ${{ inputs.version }}
        values-files: ${{ inputs.values-files }}
        values: ${{ inputs.values }}
        timeout: ${{ inputs.timeout }}
        chart-location: $CLOUDBEES_WORKSPACE/helm-chart
        max-history: ${{ inputs.max-history }}
        debug: ${{ inputs.debug }}
        dependency-build: ${{ inputs.dependency-build }}
        env-vars-file: ${{ inputs.env-vars-file }}
        wait: true
        dry-run: ${{ inputs.dry-run }}
        registry-configuration: ${{ inputs.registry-configuration }}
